#include <Arduino.h>

#define PIN_MOSFET_5V_LEDS PB14
#define PIN_MOSFET_3V3_SENSORS PB15
#define PIN_LED_DATA PC14
#define PIN_LED PC13

#define PIN_WAKE_BUTTON PB12

#define NRF24_CE PA3
#define NRF24_CSN PA4

#define I2C1_SCL_PIN PB6
#define I2C1_SDA_PIN PB7
#define I2C3_SCL_PIN PA8
#define I2C3_SDA_PIN PB4
