; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
	-std=gnu++17
	-I lib/shared_types/include
	-I lib/state_machine_framework/include
	-I lib/radio_controller/include
	-Os
	-flto
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DDEBUG_GASPETTO
	-DUNO
build_type = release
lib_deps =
	nrf24/RF24@^1.5.0
monitor_speed = 115200
upload_protocol = arduino
debug_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
extra_scripts = pre:../../../tools/pre_build.py
