; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_box_hw_test]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
upload_protocol = dfu
upload_command = dfu-util -d 0483:df11 -a 0 -s 0x08000000:leave -D $SOURCE
; upload_protocol = stlink
; debug_tool = stlink
; upload_protocol = blackmagic
; debug_tool = blackmagic
; debug_port = /dev/serial/by-id/usb-Black_Magic_Debug_Black_Magic_Probe__ST-Link_v2__v1.10.0-229-g98f11d47_A7864BB1-if00
debug_init_break = tbreak setup
debug_build_flags = -O0 -g3 -ggdb
build_type = debug
extra_scripts = pre:../../../tools/pre_build.py
lib_deps =
	Wire
	SPI
	nrf24/RF24@^1.5.0
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/Adafruit NeoPixel@^1.12.3

; Build flags indispensables pour activer l'USB Serial (CDC) de la puce
build_flags =
	-D TEST_ADS1115
	-D GBOX
	-D TEST_ADS1115_CONVERSION_READS
	; -D TEST_PIECE_THRESHOLD_CALIBRATION
	-D TEST_ADS1115_MEAN_SAMPLES=15
	-D TEST_I2C3_CLOCK_HZ=25000
	; Thresholds used for live piece label display in calibration mode
	; -D TEST_THRESHOLD_FORWARD_START=100
	; -D TEST_THRESHOLD_BACKWARD_START=700
	; -D TEST_THRESHOLD_TURN_RIGHT_START=1300
	; -D TEST_THRESHOLD_TURN_LEFT_START=1900
	; -D TEST_THRESHOLD_STOP_START=2500
	; -D TEST_THRESHOLD_LOOP_START=3100
	; -D TEST_LED_ANIMATIONS
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
