; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1
upload_protocol = dfu
build_flags =
	-I lib/shared_types/include
	-I lib/state_machine_framework/include
	-I lib/radio_controller/include
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
build_type = release
lib_deps =
	nrf24/RF24@^1.5.0
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/Adafruit NeoPixel@^1.12.3

extra_scripts = pre:../../../tools/pre_build.py
